import { Grid } from "@mui/material";
import Head from "next/head";
import MainContent from "../components/MainContent";
import Sidebar from "../components/Sidebar";

export default function Home() {
	return (
		<div>
			<Head>
				<title>Grid Manager 2.0</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Grid container>
				<Grid item sx={{ flexShrink: 0 }} xs={2}>
					<Sidebar />
				</Grid>

				<Grid item sx={{ flexGrow: 1 }} xs={10}>
					<MainContent />
				</Grid>
			</Grid>
		</div>
	);
}
